version: "3.8"

services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    # to use pdb, attach the service in a new terminal(docker attach app) because docker compose up don't allow it
    stdin_open: true
    tty: true
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:6.2-alpine

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A app.celery.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - app
      - redis

  flower:
    container_name: flower
    build: .
    command: celery -A app.celery.celery_worker.celery flower --port=5555
    ports:
      - 5556:5555
    env_file:
      - .env
    depends_on:
      - app
      - redis
      - celery_worker
